pluginManagement {
    repositories {
        maven { url 'https://files.minecraftforge.net/maven' }
        maven { url 'https://maven.parchmentmc.org' }
        mavenCentral()
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.toString() == 'org.spongepowered.mixin') {
                useModule("org.spongepowered:mixingradle:${requested.version}")
            }
        }
    }
}

rootProject.name = 'MCT-RS-Mixin'
