pluginManagement {
    repositories {
        maven { url 'https://maven.minecraftforge.net/' }
        maven { url 'https://maven.gofancy.wtf/releases' }
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

def commonProps = new Properties()
file('../common/common-1.12.properties').withInputStream { commonProps.load(it) }

def versionProps = new Properties()
file('version.properties').withInputStream { versionProps.load(it) }

rootProject.name = "MCT-RS-Mixin-${commonProps['mcversion']}-${versionProps['version']}"
